<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5f5f1658c99d1e905b37f8a5b3c9e264
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Component\\Filesystem\\' => 29,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Component\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/filesystem',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5f5f1658c99d1e905b37f8a5b3c9e264::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5f5f1658c99d1e905b37f8a5b3c9e264::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
